name: Slack Notification on Code Push

on:
  push:
    branches:
      - main

jobs:
  slack-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Code pushed to *${{ github.ref_name }}* by *${{ github.actor }}*"
          SLACK_COLOR: '#439FE0'
